let nombre = "Andreina"
let apellido = "Cabeza"
let estudiante = nombre + " " + apellido
let estudianteMayus = estudiante.toUpperCase()
let estudianteMinus = estudiante.toLowerCase()
let num = estudiante.length
let primeraletra = nombre[0]
let ultimaletra = apellido[apellido.length - 1]
let sinespacios = estudiante.trim()
let contiene = estudiante.includes(nombre)